<a href="https://colab.research.google.com/github/joseBouza17/bigdata-merval-analysis/blob/main/merval_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install yfinance pandas
import pandas as pd
import yfinance as yf

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.14.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (3.0)

In [2]:
tickers = {
    "merval": "^MERV",
    "usdars": "ARS=X",
    "vix": "^VIX"
}

start_date = "2018-01-01"
end_date = "2026-01-01"

In [3]:
merval = yf.download(tickers["merval"], start=start_date, end=end_date)
merval.head()

/tmp/ipykernel_3494/739567776.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  merval = yf.download(tickers["merval"], start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed

Price         Close     High      Low     Open Volume
Ticker        ^MERV    ^MERV    ^MERV    ^MERV  ^MERV
Date
2018-01-02  31084.0  31144.0  30066.0  30066.0      0
2018-01-03  31476.0  31497.0  30820.0  31084.0      0
2018-01-04  31952.0  32001.0  31421.0  31476.0      0
2018-01-05  32190.0  32242.0  31698.0  31952.0      0
2018-01-08  32351.0  32419.0  31880.0  32190.0      0

In [6]:
merval.columnsmerval = merval.reset_index()

# Flatten MultiIndex columns
merval.columns = [col[0] if col[1] == "" else f"{col[0]}_{col[1]}" for col in merval.columns]

# Keep only date and closing price
merval = merval[["Date", "Close_^MERV"]]

# Rename columns
merval.columns = ["date", "merval_close"]

merval.head()

/tmp/ipykernel_3494/150565829.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  merval.columnsmerval = merval.reset_index()

        date  merval_close
0 2018-01-02       31084.0
1 2018-01-03       31476.0
2 2018-01-04       31952.0
3 2018-01-05       32190.0
4 2018-01-08       32351.0

In [7]:
# Calculate daily return
merval["merval_return"] = merval["merval_close"].pct_change()

merval.head()

/tmp/ipykernel_3494/3790039943.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merval["merval_return"] = merval["merval_close"].pct_change()

        date  merval_close  merval_return
0 2018-01-02       31084.0            NaN
1 2018-01-03       31476.0       0.012611
2 2018-01-04       31952.0       0.015123
3 2018-01-05       32190.0       0.007449
4 2018-01-08       32351.0       0.005002

In [8]:
usdars = yf.download(tickers["usdars"], start=start_date, end=end_date)

usdars = usdars.reset_index()

# Flatten columns
usdars.columns = [col[0] if col[1] == "" else f"{col[0]}_{col[1]}" for col in usdars.columns]

# Keep only date and closing price
usdars = usdars[["Date", "Close_ARS=X"]]

# Rename columns
usdars.columns = ["date", "usdars_close"]

# Calculate return
usdars["usdars_return"] = usdars["usdars_close"].pct_change()

usdars.head()

/tmp/ipykernel_3494/430070859.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  usdars = yf.download(tickers["usdars"], start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed

        date  usdars_close  usdars_return
0 2018-01-01     19.087000            NaN
1 2018-01-02     18.591000      -0.025986
2 2018-01-03     18.390499      -0.010785
3 2018-01-04     18.443501       0.002882
4 2018-01-05     18.614000       0.009244

In [9]:
vix = yf.download(tickers["vix"], start=start_date, end=end_date)

vix = vix.reset_index()

# Flatten columns
vix.columns = [col[0] if col[1] == "" else f"{col[0]}_{col[1]}" for col in vix.columns]

# Keep only date and closing price
vix = vix[["Date", "Close_^VIX"]]

# Rename columns
vix.columns = ["date", "vix_close"]

# Calculate daily return
vix["vix_return"] = vix["vix_close"].pct_change()

vix.head()

/tmp/ipykernel_3494/2458159632.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  vix = yf.download(tickers["vix"], start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed

        date  vix_close  vix_return
0 2018-01-02       9.77         NaN
1 2018-01-03       9.15   -0.063460
2 2018-01-04       9.22    0.007650
3 2018-01-05       9.22    0.000000
4 2018-01-08       9.52    0.032538

In [10]:
# Merge all datasets on date
df = merval.merge(usdars, on="date", how="inner")
df = df.merge(vix, on="date", how="inner")

df.head()

,date,merval_close,merval_return,usdars_close,usdars_return,vix_close,vix_return
0,2018-01-02,31084.0,NaN,18.591000,-0.025986,9.77,NaN
1,2018-01-03,31476.0,0.012611,18.390499,-0.010785,9.15,-0.063460
2,2018-01-04,31952.0,0.015123,18.443501,0.002882,9.22,0.007650
3,2018-01-05,32190.0,0.007449,18.614000,0.009244,9.22,0.000000
4,2018-01-08,32351.0,0.005002,18.577000,-0.001988,9.52,0.032538

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1893 entries, 0 to 1892
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1893 non-null   datetime64[ns]
 1   merval_close   1893 non-null   float64
 2   merval_return  1892 non-null   float64
 3   usdars_close   1893 non-null   float64
 4   usdars_return  1893 non-null   float64
 5   vix_close      1893 non-null   float64
 6   vix_return     1892 non-null   float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 103.7 KB

In [12]:
df = df.dropna()

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1892 entries, 1 to 1892
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1892 non-null   datetime64[ns]
 1   merval_close   1892 non-null   float64
 2   merval_return  1892 non-null   float64
 3   usdars_close   1892 non-null   float64
 4   usdars_return  1892 non-null   float64
 5   vix_close      1892 non-null   float64
 6   vix_return     1892 non-null   float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 118.2 KB

In [13]:
import sys
!{sys.executable} -m pip install google-auth google-cloud-bigquery pyarrow db-dtypes

Requirement already satisfied: google-auth in /usr/local/lib/python3.12/dist-packages (2.47.0)
Requirement already satisfied: google-cloud-bigquery in /usr/local/lib/python3.12/dist-packages (3.41.0)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Requirement already satisfied: db-dtypes in /usr/local/lib/python3.12/dist-packages (1.5.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth) (4.9.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.11.1 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (2.30.1)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.5.1)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.8.2)
Requirement already satisfied: packaging>=24.2.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (26.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.32.4)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from db-dtypes) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=1.5.3 in /usr/local/lib/python3.12/dist-packages (from db-dtypes) (2.2.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.73.1)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.27.2)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.80.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.71.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.8.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=1.5.3->db-dtypes) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=1.5.3->db-dtypes) (2025.3)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth) (0.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2026.2.25)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (4.15.0)

In [14]:
from google.colab import auth
auth.authenticate_user()

from google.cloud import bigquery

PROJECT_ID = "poetic-maxim-488617-k9"
DATASET_ID = "market_data"
TABLE_ID = "merval_macro"

client = bigquery.Client(project=PROJECT_ID)

print("Connected to BigQuery successfully")

Connected to BigQuery successfully

In [15]:
df = df.dropna().copy()
df["date"] = pd.to_datetime(df["date"], errors="coerce")

In [16]:
dataset_ref = bigquery.Dataset(f"{PROJECT_ID}.{DATASET_ID}")
dataset_ref.location = "US"

client.create_dataset(dataset_ref, exists_ok=True)

print(f"Dataset ready: {PROJECT_ID}.{DATASET_ID}")

Dataset ready: poetic-maxim-488617-k9.market_data

In [17]:
full_table_id = f"{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}"

job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE"
)

job = client.load_table_from_dataframe(
    df,
    full_table_id,
    job_config=job_config
)

job.result()

print(f"Upload finished: {full_table_id}")
print(f"Rows uploaded: {len(df)}")

Upload finished: poetic-maxim-488617-k9.market_data.merval_macro
Rows uploaded: 1892